/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apple.istore;

import java.awt.Color;

/**
 *
 * @author Heoug
 */
public class CashierUI extends javax.swing.JFrame {

    /**
     * Creates new form CashierUI
     */
    Color DefaultColor,ClickColor;
    public CashierUI() {
        initComponents();
        centerWindow();
        DefaultColor=new Color(251,251,251);
        ClickColor=new Color(215, 215, 215);
        
                //set defualt color to button panel on run time
        //jPanelSearch.setBackground(DefaultColor);
        jPanelProducts.setBackground(DefaultColor);
        jPanelHowtouse.setBackground(DefaultColor);
        jPanelSignOut.setBackground(DefaultColor);
    }
    
    private void centerWindow() { // to make the program always open at middle of the screen
    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    int screenWidth = screenSize.width;
    int screenHeight = screenSize.height;
    int frameWidth = getWidth();
    int frameHeight = getHeight();
    setLocation((screenWidth - frameWidth) / 2, (screenHeight - frameHeight) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelProducts = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelHowtouse = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelSignOut = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMenuName = new javax.swing.JLabel();
        jLabelMenuDetails = new javax.swing.JLabel();
        jOutputPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Apple Logo Istorepx.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jPanelProducts.setBackground(new java.awt.Color(251, 251, 251));
        jPanelProducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelProducts.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelProducts.setPreferredSize(new java.awt.Dimension(188, 39));
        jPanelProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelProductsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelProductsMousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(251, 251, 251));
        jLabel8.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Shopping Cart.png"))); // NOI18N
        jLabel8.setText("Products");

        javax.swing.GroupLayout jPanelProductsLayout = new javax.swing.GroupLayout(jPanelProducts);
        jPanelProducts.setLayout(jPanelProductsLayout);
        jPanelProductsLayout.setHorizontalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelProductsLayout.setVerticalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelHowtouse.setBackground(new java.awt.Color(251, 251, 251));
        jPanelHowtouse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelHowtouse.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelHowtouse.setPreferredSize(new java.awt.Dimension(188, 41));
        jPanelHowtouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelHowtouseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHowtouseMousePressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(251, 251, 251));
        jLabel9.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Question Mark.png"))); // NOI18N
        jLabel9.setText("How to Use");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout jPanelHowtouseLayout = new javax.swing.GroupLayout(jPanelHowtouse);
        jPanelHowtouse.setLayout(jPanelHowtouseLayout);
        jPanelHowtouseLayout.setHorizontalGroup(
            jPanelHowtouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHowtouseLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanelHowtouseLayout.setVerticalGroup(
            jPanelHowtouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHowtouseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSignOut.setBackground(new java.awt.Color(251, 251, 251));
        jPanelSignOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelSignOut.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelSignOut.setPreferredSize(new java.awt.Dimension(167, 41));
        jPanelSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSignOutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSignOutMousePressed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(251, 251, 251));
        jLabel10.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logout Rounded.png"))); // NOI18N
        jLabel10.setText("Sign Out");

        javax.swing.GroupLayout jPanelSignOutLayout = new javax.swing.GroupLayout(jPanelSignOut);
        jPanelSignOut.setLayout(jPanelSignOutLayout);
        jPanelSignOutLayout.setHorizontalGroup(
            jPanelSignOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignOutLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignOutLayout.setVerticalGroup(
            jPanelSignOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelHowtouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jPanelProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelHowtouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 570));

        jPanel2.setBackground(new java.awt.Color(251, 251, 251));
        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.setMinimumSize(new java.awt.Dimension(770, 74));
        jPanel2.setPreferredSize(new java.awt.Dimension(770, 74));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 28, 29));
        jLabel2.setText("Cashier");
        jLabel2.setMaximumSize(new java.awt.Dimension(69, 23));
        jLabel2.setMinimumSize(new java.awt.Dimension(69, 23));
        jLabel2.setPreferredSize(new java.awt.Dimension(69, 23));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 6, -1, 68));

        jLabelMenuName.setBackground(new java.awt.Color(251, 251, 251));
        jLabelMenuName.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabelMenuName.setText("Welcome");
        jLabelMenuName.setToolTipText("");
        jPanel2.add(jLabelMenuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 29, -1, -1));

        jLabelMenuDetails.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMenuDetails.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        jLabelMenuDetails.setForeground(new java.awt.Color(183, 183, 183));
        jLabelMenuDetails.setText("To the Application!");
        jLabelMenuDetails.setToolTipText("");
        jPanel2.add(jLabelMenuDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 50, 450, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 800, 80));

        jOutputPanel.setBackground(new java.awt.Color(242, 242, 242));
        jOutputPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        jOutputPanel.setPreferredSize(new java.awt.Dimension(800, 490));

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome to Apple iStore Application!");

        jLabel11.setFont(new java.awt.Font("SF Pro Display", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("You're Logged in as a Cashier!");

        javax.swing.GroupLayout jOutputPanelLayout = new javax.swing.GroupLayout(jOutputPanel);
        jOutputPanel.setLayout(jOutputPanelLayout);
        jOutputPanelLayout.setHorizontalGroup(
            jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOutputPanelLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jOutputPanelLayout.setVerticalGroup(
            jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOutputPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        getContentPane().add(jOutputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 800, 490));

        jPanel4.setBackground(new java.awt.Color(251, 251, 251));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 40));

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("-");
        jLabel5.setToolTipText("");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(251, 251, 251));
        jPanel5.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(905, 28));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Apple Logo ui.png"))); // NOI18N
        jLabel6.setText("Apple iStore Application");
        jLabel6.setMaximumSize(new java.awt.Dimension(147, 16));
        jLabel6.setMinimumSize(new java.awt.Dimension(147, 16));
        jLabel6.setPreferredSize(new java.awt.Dimension(147, 16));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(754, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1000, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProductsMousePressed
        //jPanelSearch.setBackground(DefaultColor);
        jPanelProducts.setBackground(ClickColor);
        jPanelHowtouse.setBackground(DefaultColor);
        jPanelSignOut.setBackground(DefaultColor);
        
        // renames jLabelMenuName, jLabelMenuDetails while switching through the tabs
        jLabelMenuName.setText("Products");
        jLabelMenuDetails.setText("Details of the Products");
    }//GEN-LAST:event_jPanelProductsMousePressed

    private void jPanelHowtouseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHowtouseMousePressed
        //jPanelSearch.setBackground(DefaultColor);
        jPanelProducts.setBackground(DefaultColor);
        jPanelHowtouse.setBackground(ClickColor);
        jPanelSignOut.setBackground(DefaultColor);
        
        // renames jLabelMenuName, jLabelMenuDetails while switching through the tabs
        jLabelMenuName.setText("How to Use");
        jLabelMenuDetails.setText("Instructions on how to use the application");
    }//GEN-LAST:event_jPanelHowtouseMousePressed

    private void jPanelSignOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSignOutMousePressed
        //jPanelSearch.setBackground(DefaultColor);
        jPanelProducts.setBackground(DefaultColor);
        jPanelHowtouse.setBackground(DefaultColor);
        jPanelSignOut.setBackground(ClickColor);
        
        // renames jLabelMenuName, jLabelMenuDetails while switching through the tabs
        jLabelMenuName.setText("Sign Out");
        jLabelMenuDetails.setText("");
    }//GEN-LAST:event_jPanelSignOutMousePressed

    private void jPanelProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProductsMouseClicked
        PanelProducts Pproducts = new PanelProducts();
        jOutputPanel.removeAll();
        jOutputPanel.add(Pproducts).setVisible(true);
    }//GEN-LAST:event_jPanelProductsMouseClicked

    private void jPanelHowtouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHowtouseMouseClicked
        PanelHowtouse Phowtouse = new PanelHowtouse();
        jOutputPanel.removeAll();
        jOutputPanel.add(Phowtouse).setVisible(true);
    }//GEN-LAST:event_jPanelHowtouseMouseClicked

    private void jPanelSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSignOutMouseClicked
        dispose();
        Loginportal loginPortal = new Loginportal();
        loginPortal.setVisible(true);
    }//GEN-LAST:event_jPanelSignOutMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        dispose(); // exit
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        setState(Loginportal.ICONIFIED); // minimize application
    }//GEN-LAST:event_jLabel5MouseClicked

    // To drag and move the program
    private int xMouse, yMouse;
    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanel5MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMenuDetails;
    private javax.swing.JLabel jLabelMenuName;
    private javax.swing.JPanel jOutputPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelHowtouse;
    private javax.swing.JPanel jPanelProducts;
    private javax.swing.JPanel jPanelSignOut;
    // End of variables declaration//GEN-END:variables
}
