/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apple.istore;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author Heoug
 */
public class ManagerUI extends javax.swing.JFrame {

    /**
     * Creates new form ManagerUI
     */
    
    Color DefaultColor,ClickColor;
    public ManagerUI() {
        initComponents();
        centerWindow();
        JPanel contentPanel = (JPanel) getContentPane();
        contentPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 9));
        DefaultColor=new Color(251,251,251);
        ClickColor=new Color(215, 215, 215);
        
        //set defualt color to button panel on run time
        //jPanelSearch.setBackground(DefaultColor);
        jPanelProducts.setBackground(DefaultColor);
        jPanelManageProducts.setBackground(DefaultColor);
        jPanelCreateAcc.setBackground(DefaultColor);
        jPanelHowtouse.setBackground(DefaultColor);
        jPanelSignOut.setBackground(DefaultColor); 
    }
    
    private void centerWindow() { // to make the program always open at middle of the screen
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;
        int frameWidth = getWidth();
        int frameHeight = getHeight();
        setLocation((screenWidth - frameWidth) / 2, (screenHeight - frameHeight) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelProducts = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelManageProducts = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelCreateAcc = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelHowtouse = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelSignOut = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelDeleteProducts = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMenuName = new javax.swing.JLabel();
        jLabelMenuDetails = new javax.swing.JLabel();
        jOutputPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMovePanelManager = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Apple Logo Istorepx.png"))); // NOI18N

        jPanelProducts.setBackground(new java.awt.Color(251, 251, 251));
        jPanelProducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelProductsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelProductsMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(251, 251, 251));
        jLabel7.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Shopping Cart.png"))); // NOI18N
        jLabel7.setText("Products");

        javax.swing.GroupLayout jPanelProductsLayout = new javax.swing.GroupLayout(jPanelProducts);
        jPanelProducts.setLayout(jPanelProductsLayout);
        jPanelProductsLayout.setHorizontalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelProductsLayout.setVerticalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelManageProducts.setBackground(new java.awt.Color(251, 251, 251));
        jPanelManageProducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelManageProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelManageProductsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelManageProductsMousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(251, 251, 251));
        jLabel8.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        jLabel8.setText("Add Products");

        javax.swing.GroupLayout jPanelManageProductsLayout = new javax.swing.GroupLayout(jPanelManageProducts);
        jPanelManageProducts.setLayout(jPanelManageProductsLayout);
        jPanelManageProductsLayout.setHorizontalGroup(
            jPanelManageProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageProductsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanelManageProductsLayout.setVerticalGroup(
            jPanelManageProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCreateAcc.setBackground(new java.awt.Color(251, 251, 251));
        jPanelCreateAcc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelCreateAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCreateAccMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelCreateAccMousePressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(251, 251, 251));
        jLabel9.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Account.png"))); // NOI18N
        jLabel9.setText("Create New Account");

        javax.swing.GroupLayout jPanelCreateAccLayout = new javax.swing.GroupLayout(jPanelCreateAcc);
        jPanelCreateAcc.setLayout(jPanelCreateAccLayout);
        jPanelCreateAccLayout.setHorizontalGroup(
            jPanelCreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateAccLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCreateAccLayout.setVerticalGroup(
            jPanelCreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateAccLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelHowtouse.setBackground(new java.awt.Color(251, 251, 251));
        jPanelHowtouse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelHowtouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelHowtouseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHowtouseMousePressed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(251, 251, 251));
        jLabel10.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Question Mark.png"))); // NOI18N
        jLabel10.setText("How to Use");

        javax.swing.GroupLayout jPanelHowtouseLayout = new javax.swing.GroupLayout(jPanelHowtouse);
        jPanelHowtouse.setLayout(jPanelHowtouseLayout);
        jPanelHowtouseLayout.setHorizontalGroup(
            jPanelHowtouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHowtouseLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelHowtouseLayout.setVerticalGroup(
            jPanelHowtouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHowtouseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSignOut.setBackground(new java.awt.Color(251, 251, 251));
        jPanelSignOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSignOutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSignOutMousePressed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(251, 251, 251));
        jLabel11.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logout Rounded.png"))); // NOI18N
        jLabel11.setText("Sign Out");

        javax.swing.GroupLayout jPanelSignOutLayout = new javax.swing.GroupLayout(jPanelSignOut);
        jPanelSignOut.setLayout(jPanelSignOutLayout);
        jPanelSignOutLayout.setHorizontalGroup(
            jPanelSignOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignOutLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignOutLayout.setVerticalGroup(
            jPanelSignOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelDeleteProducts.setBackground(new java.awt.Color(251, 251, 251));
        jPanelDeleteProducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelDeleteProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDeleteProductsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelDeleteProductsMousePressed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(251, 251, 251));
        jLabel14.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        jLabel14.setText("Delete Products");

        javax.swing.GroupLayout jPanelDeleteProductsLayout = new javax.swing.GroupLayout(jPanelDeleteProducts);
        jPanelDeleteProducts.setLayout(jPanelDeleteProductsLayout);
        jPanelDeleteProductsLayout.setHorizontalGroup(
            jPanelDeleteProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteProductsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDeleteProductsLayout.setVerticalGroup(
            jPanelDeleteProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelManageProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCreateAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelHowtouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelDeleteProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jPanelProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelManageProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDeleteProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCreateAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelHowtouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 570));

        jPanel2.setBackground(new java.awt.Color(251, 251, 251));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 28, 29));
        jLabel2.setText("Manager");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 6, -1, 68));

        jLabelMenuName.setBackground(new java.awt.Color(251, 251, 251));
        jLabelMenuName.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabelMenuName.setText("Welcome");
        jPanel2.add(jLabelMenuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 29, -1, -1));

        jLabelMenuDetails.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMenuDetails.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        jLabelMenuDetails.setForeground(new java.awt.Color(183, 183, 183));
        jLabelMenuDetails.setText("To the Application!");
        jPanel2.add(jLabelMenuDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 50, 450, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 800, 80));

        jOutputPanel.setBackground(new java.awt.Color(242, 242, 242));

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome to Apple iStore Application!");

        jLabel12.setFont(new java.awt.Font("SF Pro Display", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("You're Logged in as a Manager!");

        javax.swing.GroupLayout jOutputPanelLayout = new javax.swing.GroupLayout(jOutputPanel);
        jOutputPanel.setLayout(jOutputPanelLayout);
        jOutputPanelLayout.setHorizontalGroup(
            jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOutputPanelLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jOutputPanelLayout.setVerticalGroup(
            jOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOutputPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        getContentPane().add(jOutputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 800, 490));

        jPanel4.setBackground(new java.awt.Color(251, 251, 251));

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jMovePanelManager.setBackground(new java.awt.Color(248, 248, 248));
        jMovePanelManager.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMovePanelManagerMouseDragged(evt);
            }
        });
        jMovePanelManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMovePanelManagerMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Apple Logo ui.png"))); // NOI18N
        jLabel6.setText("Apple iStore Application");

        javax.swing.GroupLayout jMovePanelManagerLayout = new javax.swing.GroupLayout(jMovePanelManager);
        jMovePanelManager.setLayout(jMovePanelManagerLayout);
        jMovePanelManagerLayout.setHorizontalGroup(
            jMovePanelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMovePanelManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(733, Short.MAX_VALUE))
        );
        jMovePanelManagerLayout.setVerticalGroup(
            jMovePanelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("-");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jMovePanelManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMovePanelManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1000, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        setState(Loginportal.ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private int xMouse, yMouse;
    private void jMovePanelManagerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMovePanelManagerMousePressed
        // use MousePressed, MouseDragged to make the frame movable.
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jMovePanelManagerMousePressed

    private void jMovePanelManagerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMovePanelManagerMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jMovePanelManagerMouseDragged

    private void jPanelProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProductsMousePressed
        //jPanelSearch.setBackground(DefaultColor);
        jPanelProducts.setBackground(ClickColor);
        jPanelManageProducts.setBackground(DefaultColor);
        jPanelDeleteProducts.setBackground(DefaultColor);
        jPanelCreateAcc.setBackground(DefaultColor);
        jPanelHowtouse.setBackground(DefaultColor);
        jPanelSignOut.setBackground(DefaultColor);
        
        // renames jLabelMenuName, jLabelMenuDetails while switching through the tabs
        jLabelMenuName.setText("Products");
        jLabelMenuDetails.setText("Details of the Products");
    }//GEN-LAST:event_jPanelProductsMousePressed

    private void jPanelManageProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelManageProductsMousePressed
        //jPanelSearch.setBackground(DefaultColor);
        jPanelProducts.setBackground(DefaultColor);
        jPanelManageProducts.setBackground(ClickColor);
        jPanelDeleteProducts.setBackground(DefaultColor);
        jPanelCreateAcc.setBackground(DefaultColor);
        jPanelHowtouse.setBackground(DefaultColor);
        jPanelSignOut.setBackground(DefaultColor);
        
        // renames jLabelMenuName, jLabelMenuDetails while switching through the tabs
        jLabelMenuName.setText("Add Products");
        jLabelMenuDetails.setText("");
    }//GEN-LAST:event_jPanelManageProductsMousePressed

    private void jPanelCreateAccMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCreateAccMousePressed
        //jPanelSearch.setBackground(DefaultColor);
        jPanelProducts.setBackground(DefaultColor);
        jPanelManageProducts.setBackground(DefaultColor);
        jPanelDeleteProducts.setBackground(DefaultColor);
        jPanelCreateAcc.setBackground(ClickColor);
        jPanelHowtouse.setBackground(DefaultColor);
        jPanelSignOut.setBackground(DefaultColor);
        
        // renames jLabelMenuName, jLabelMenuDetails while switching through the tabs
        jLabelMenuName.setText("Create New Account");
        jLabelMenuDetails.setText("Create New Manager/Cashier Accounts");
    }//GEN-LAST:event_jPanelCreateAccMousePressed

    private void jPanelHowtouseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHowtouseMousePressed
        //jPanelSearch.setBackground(DefaultColor);
        jPanelProducts.setBackground(DefaultColor);
        jPanelManageProducts.setBackground(DefaultColor);
        jPanelDeleteProducts.setBackground(DefaultColor);
        jPanelCreateAcc.setBackground(DefaultColor);
        jPanelHowtouse.setBackground(ClickColor);
        jPanelSignOut.setBackground(DefaultColor);
        
        // renames jLabelMenuName, jLabelMenuDetails while switching through the tabs
        jLabelMenuName.setText("How to Use");
        jLabelMenuDetails.setText("Instructions on how to use the application");
    }//GEN-LAST:event_jPanelHowtouseMousePressed

    private void jPanelSignOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSignOutMousePressed
        //jPanelSearch.setBackground(DefaultColor);
        jPanelProducts.setBackground(DefaultColor);
        jPanelManageProducts.setBackground(DefaultColor);
        jPanelDeleteProducts.setBackground(DefaultColor);
        jPanelCreateAcc.setBackground(DefaultColor);
        jPanelHowtouse.setBackground(DefaultColor);
        jPanelSignOut.setBackground(ClickColor);
        
        // renames jLabelMenuName, jLabelMenuDetails while switching through the tabs
        jLabelMenuName.setText("Sign Out");
        jLabelMenuDetails.setText("");
    }//GEN-LAST:event_jPanelSignOutMousePressed

    private void jPanelProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProductsMouseClicked
        PanelProducts Pproducts = new PanelProducts();
        jOutputPanel.removeAll();
        jOutputPanel.add(Pproducts).setVisible(true);
    }//GEN-LAST:event_jPanelProductsMouseClicked

    private void jPanelManageProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelManageProductsMouseClicked
        PanelAddProducts PAddProducts = new PanelAddProducts();
        jOutputPanel.removeAll();
        jOutputPanel.add(PAddProducts).setVisible(true);
    }//GEN-LAST:event_jPanelManageProductsMouseClicked

    private void jPanelCreateAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCreateAccMouseClicked
        PanelCreateAccounts Pcreateaccounts = new PanelCreateAccounts();
        jOutputPanel.removeAll();
        jOutputPanel.add(Pcreateaccounts).setVisible(true);
    }//GEN-LAST:event_jPanelCreateAccMouseClicked

    private void jPanelHowtouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHowtouseMouseClicked
        PanelHowtouse Phowtouse = new PanelHowtouse();
        jOutputPanel.removeAll();
        jOutputPanel.add(Phowtouse).setVisible(true);
    }//GEN-LAST:event_jPanelHowtouseMouseClicked

    private void jPanelSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSignOutMouseClicked
        dispose();
        Loginportal loginPortal = new Loginportal();
        loginPortal.setVisible(true);
    }//GEN-LAST:event_jPanelSignOutMouseClicked

    private void jPanelDeleteProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeleteProductsMouseClicked
        PanelDeleteProducts Pdeleteproducts = new PanelDeleteProducts();
        jOutputPanel.removeAll();
        jOutputPanel.add(Pdeleteproducts).setVisible(true);
    }//GEN-LAST:event_jPanelDeleteProductsMouseClicked

    private void jPanelDeleteProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeleteProductsMousePressed
        //jPanelSearch.setBackground(DefaultColor);
        jPanelProducts.setBackground(DefaultColor);
        jPanelManageProducts.setBackground(DefaultColor);
        jPanelDeleteProducts.setBackground(ClickColor);
        jPanelCreateAcc.setBackground(DefaultColor);
        jPanelHowtouse.setBackground(DefaultColor);
        jPanelSignOut.setBackground(DefaultColor);
        
        jLabelMenuName.setText("Delete Products");
        jLabelMenuDetails.setText("");
    }//GEN-LAST:event_jPanelDeleteProductsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMenuDetails;
    private javax.swing.JLabel jLabelMenuName;
    private javax.swing.JPanel jMovePanelManager;
    private javax.swing.JPanel jOutputPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCreateAcc;
    private javax.swing.JPanel jPanelDeleteProducts;
    private javax.swing.JPanel jPanelHowtouse;
    private javax.swing.JPanel jPanelManageProducts;
    private javax.swing.JPanel jPanelProducts;
    private javax.swing.JPanel jPanelSignOut;
    // End of variables declaration//GEN-END:variables
}
